import { useState } from 'react';

function formatConfidence(c) {
  if (c == null) return '—';
  return Math.round(c * 100) + '%';
}

function confidenceClass(c) {
  if (c == null) return 'confidence-bar confidence-low';
  if (c >= 0.75) return 'confidence-bar confidence-high';
  if (c >= 0.5)  return 'confidence-bar confidence-mid';
  return 'confidence-bar confidence-low';
}

export function SuggestionCard({ suggestion, onResolved }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);

  const isAgentic = suggestion.triggerReason === 'AGENT_OFFLINE';
  const confidencePct = suggestion.confidence == null ? 0 : Math.round(suggestion.confidence * 100);

  async function handle(action) {
    setBusy(true);
    setError(null);
    try {
      await onResolved(suggestion.id, action);
    } catch (e) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <article className="card suggestion">
      <header className="suggestion-head">
        <div className="suggestion-title">
          <span className="order-id">{suggestion.orderId}</span>
          {isAgentic
            ? <span className="badge badge-agentic" title="Auto-generated by the agentic re-plan loop">AGENTIC</span>
            : <span className="badge badge-manual" title="Manually requested via /orders/{id}/suggest">MANUAL</span>
          }
        </div>
        <div className="suggestion-meta">#{suggestion.id} · created {new Date(suggestion.createdAt).toLocaleTimeString()}</div>
      </header>

      <div className="suggestion-rec">
        <div className="rec-label">Recommended agent</div>
        <div className="rec-agent">
          {suggestion.recommendedAgentName || '(unresolved)'}
          <span className="rec-agent-id"> {suggestion.recommendedAgentId ? `(${suggestion.recommendedAgentId})` : ''}</span>
        </div>
      </div>

      <div className="suggestion-confidence">
        <div className="confidence-header">
          <span>AI confidence</span>
          <span className="confidence-value">{formatConfidence(suggestion.confidence)}</span>
        </div>
        <div className="confidence-track">
          <div className={confidenceClass(suggestion.confidence)} style={{ width: confidencePct + '%' }} />
        </div>
      </div>

      <div className="suggestion-reasoning">
        <div className="reasoning-label">Reasoning</div>
        <p>{suggestion.reasoning || <em>(no reasoning provided)</em>}</p>
      </div>

      {error && <div className="error-line">{error}</div>}

      <footer className="suggestion-actions">
        <button
          className="btn btn-accept"
          disabled={busy || !suggestion.recommendedAgentId}
          onClick={() => handle('ACCEPTED')}
        >
          {busy ? 'Working…' : 'Accept'}
        </button>
        <button
          className="btn btn-reject"
          disabled={busy}
          onClick={() => handle('REJECTED')}
        >
          Reject
        </button>
      </footer>
    </article>
  );
}
