package com.example.demo.entity;

public enum TriggerReason {
    /**
     * Suggestion was manually requested for an order that has not yet been assigned
     * (e.g. at order creation time or via a direct API call).
     * Rendered in the UI without any special badge.
     */
    INITIAL,

    /**
     * Suggestion was auto-generated by the T-4 agentic re-planning loop because
     * the currently assigned agent transitioned to OFFLINE.
     * Rendered in the UI with the "AGENTIC" badge.
     */
    AGENT_OFFLINE
}
